language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
branches:
  only:
    - master
    - develop
install:
  - yarn
before_script:
  - yarn lint
  - yarn lint:test
  - yarn test
script:
  - yarn build
after_success:
  - yarn test:coveralls
